### ISSUE TITLE
How are "Applications credentials in configuration files" identified?

### ISSUE THREAD

**Issue by funkypenguin** [armosec/kubescape#16]
kubescape flagged the following for me:

```
[control: Applications credentials in configuration files] failed 😥
Description: Attackers who have access to configuration files can steal the stored secrets and use them. Checks if ConfigMaps or pods have sensitive information in configuration.
   Namespace vault
      StatefulSet - cluster-vault
      ConfigMap - istio-ca-root-cert
      ConfigMap - kube-root-ca.crt
```

Now the Istio certs I understand and don't care about, but I'm unsure what the credential referenced by the cluster-vault statefulset is. Here's my statefulset spec:

```
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      vault_cr: cluster-vault
  serviceName: ""
  template:
    metadata:
      annotations:
        post.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--unfreeze", "/vault/file/"]'
        post.hook.backup.velero.io/container: velero-fsfreeze
        pre.hook.backup.velero.io/command: '["/sbin/fsfreeze", "--freeze", "/vault/file/"]'
        pre.hook.backup.velero.io/container: velero-fsfreeze
        prometheus.io/path: /metrics
        prometheus.io/port: "9102"
        prometheus.io/scrape: "true"
        vault.banzaicloud.io/tls-expiration-date: "2022-08-13T01:01:57Z"
        vault.banzaicloud.io/vault-config: 4ec986d4017ab76183972683a716b881fe599a89508ba3100b7ba6a7f366cf9f
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: vault
        vault_cr: cluster-vault
    spec:
      affinity: {}
      automountServiceAccountToken: true
      containers:
      - args:
        - server
        env:
        - name: VAULT_K8S_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: VAULT_LOG_LEVEL
          value: debug
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-credentials
        image: redacted/vault:1.8.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/sys/init
            port: https-api-port
            scheme: HTTPS
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: vault
        ports:
        - containerPort: 8201
          name: cluster-port
          protocol: TCP
        - containerPort: 8300
          name: external-port
          protocol: TCP
        - containerPort: 8280
          name: http-api-port
          protocol: TCP
        - containerPort: 8200
          name: https-api-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /v1/sys/health?standbyok=true&perfstandbyok=true&drsecondarycode=299
            port: https-api-port
            scheme: HTTPS
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: 1m
            memory: 256Mi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SETFCAP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vault/config
          name: vault-config
        - mountPath: /vault/raft
          name: vault-raft
        - mountPath: /vault/tls
          name: vault-tls
      - args:
        - --pre-flight-checks
        - "true"
        - --mode
        - k8s
        - --k8s-secret-namespace
        - vault
        - --k8s-secret-name
        - cluster-vault-unseal-keys
        - --k8s-secret-labels
        - app.kubernetes.io/name=vault,vault_cr=cluster-vault
        command:
        - bank-vaults
        - unseal
        - --init
        - --auto
        - --raft
        - --raft-leader-address
        - https://cluster-vault:8200
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: VAULT_ADDR
          value: https://127.0.0.1:8200
        - name: VAULT_CACERT
          value: /vault/tls/ca.crt
        image: redacted/bank-vaults:1.13.1
        imagePullPolicy: IfNotPresent
        name: bank-vaults
        ports:
        - containerPort: 9091
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: "5"
            memory: 64Mi
          requests:
            cpu: 1m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vault/tls
          name: vault-tls
      - args:
        - --statsd.mapping-config=/tmp/statsd-mapping.conf
        image: redacted/statsd-exporter:v0.12.2
        imagePullPolicy: IfNotPresent
        name: prometheus-exporter
        ports:
        - containerPort: 9125
          name: statsd
          protocol: UDP
        - containerPort: 9102
          name: prometheus
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 32Mi
          requests:
            cpu: 1m
            memory: 16Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/
          name: statsd-mapping
      - command:
        - /bin/bash
        - -c
        - sleep infinity
        image: redacted/debian:10-slim
        imagePullPolicy: IfNotPresent
        name: velero-fsfreeze
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vault/raft
          name: vault-raft
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - template
        - -template
        - /tmp/vault-config.json:/vault/config/vault.json
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: VAULT_LOG_LEVEL
          value: debug
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-credentials
        image: redacted/bank-vaults:1.13.1
        imagePullPolicy: IfNotPresent
        name: config-templating
        resources:
          limits:
            cpu: "2"
            memory: 512Mi
          requests:
            cpu: 1m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vault/config
          name: vault-config
        - mountPath: /vault/raft
          name: vault-raft
        - mountPath: /tmp
          name: vault-raw-config
        - mountPath: /vault/tls
          name: vault-tls
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      serviceAccount: vault
      serviceAccountName: vault
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: cluster-vault-statsd-mapping
        name: statsd-mapping
      - emptyDir:
          medium: Memory
          sizeLimit: 1Mi
        name: vault-config
      - name: vault-raw-config
        secret:
          defaultMode: 420
          secretName: cluster-vault-raw-config
      - name: vault-tls
        secret:
          defaultMode: 420
          secretName: cluster-vault-tls
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: vault-raft
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: topolvm-provisioner
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: cluster-vault-55dd98fc9c
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: cluster-vault-55dd98fc9c
  updatedReplicas: 3
```

Where are the alleged application credentials hiding? :)

Thanks!
D
