### ISSUE TITLE
Possible false positives on C-0059 - CVE-2021-25742-nginx-ingress-snippet-annotation-vulnerability

### ISSUE THREAD

**Issue by tim-sendible** [armosec/kubescape#197]
Running `kubescape scan control c-0059` using the `:latest` docker image within an EKS 1.21 cluster.

This reports that all 4 of my ingress controllers have failed, yet all 4 have the following in their configmap:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.0.4
  name: nginx-controller
data:
...
  allow-snippet-annotations: “false”
...
```
