### ISSUE TITLE
Helm deployed kubescape cronjob config read issue

### ISSUE THREAD

**Issue by jonaskint** [armosec/kubescape#301]
I'm trying to set up the armo-collector setup on our k8s clusters and ran into an issue with the kubescape cronjob. When the scan finishes, it's complaining about the account ID and cluster name not being set. I'm currently tracking down where this issue could originate myself, but I'll post some extra information here in the meanwhile.

Part of the log:
```
...
+-----------------------------------------------------------------------+------------------+--------------------+---------------+--------------+
|                           RESOURCE SUMMARY                            |       1225       |         0          |     9103      |    21.79%    |
+-----------------------------------------------------------------------+------------------+--------------------+---------------+--------------+
missing accout ID or cluster name. AccountID: '', Cluster name: ''
```

I deployed everything through helm and saw that this configmap is used by the cronjob. I double checked the configuration parameters and everything looks in order. Here is an example of my config:
```yaml
apiVersion: v1
data:
  config.json: |
    {
      "customerGUID": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
      "clusterName": "someClusterName"
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: armo
    meta.helm.sh/release-namespace: armo-system
  creationTimestamp: "2022-01-05T11:13:55Z"
  labels:
    app: armo-kubescape
    app.kubernetes.io/managed-by: Helm
    tier: armo-system-control-plane
  name: armo-kubescape-config
  namespace: armo-system
```

I also found a typo when troubleshooting this issue: https://github.com/armosec/kubescape/pull/300
