### ISSUE TITLE
Ingress and Egress blocker complaining a deploy yaml - C-0030 - Ingress and Egress blocked

### ISSUE THREAD

**Issue by ZacHaque** [armosec/kubescape#327]
I am scanning a deployment yaml  - 

Command ran - 
`kubescape scan framework nsa deploy.yaml` 

Content of deploy.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bb
  name: gooddeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bb
  template:
    metadata:
      labels:
        app: bb
    spec:
      # hostNetwork: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: busybox
          image: busybox
          command: [ "sh", "-c", "sleep 1h" ]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            limits:
              memory: 96Mi
              cpu: 1
```
**Expected** :  Risk score 0%
**Actual result** : getting Risk score 100% for **Ingress and Egress blocked** 

How C-0030 applies here when deployment definition does not specify network policy. I tired to put a all deny network policy in the same yaml file,  with with selector matching label of the pod to get pass, but not helpful. what I am doing wrong here, hope someone knows the answer. Thanks in advance.

**Comment by slashben** [comment]
@ZacHaque , good point. We are checking!

**Comment by charlrvd** [comment]
I think I am in a similar situation at the moment where I wanted to pass that control and added network policies for all my deployments.
I can see the control is passing for the NetworkPolicy templates but still fails for the related deployments, even though they have the proper matchLabels.
```
control: Ingress and Egress blocked - https://hub.armo.cloud/docs/c-0030] failed 😥
Failed:
  Deployment - service1-deployment 
  Deployment - service2-deployment 
Passed:
  Namescape default
    NetworkPolicy - default-deny-all 
  NetworkPolicy - service1-network-policy 
  NetworkPolicy - service2-network-policy 
```
I expected the initial error on my deployment to be caused by the lack of NetworkPolicy to be associated with each deployments label. It's possible i understood the control wrong however.
Also I am only running kubescape against the yaml files at this point and maybe this control needs access to a remote cluster?

**Comment by Daniel-GrunbergerCA** [comment]
Hello @ZacHaque 
I am trying to reproduce your issue. I used the following yaml for it:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: test2
  labels:
    role: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 172.17.0.0/16
        except:
        - 172.17.1.0/24
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - protocol: TCP
      port: 6379
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.0/24
    ports:
    - protocol: TCP
      port: 5978
```
It seems to work fine (it passes control 0030 for this resources) both when running kubescape against the cluster and against the yaml file.
Can you please send your yaml file with deployment and network policy so I can reproduce it?
Thank you
