### ISSUE TITLE
JUnit reporting marks excluded as failed.

### ISSUE THREAD

**Issue by wim-de-groot** [armosec/kubescape#409]
**Problem**
The exceptions seem not to be formatted in the right way while reporting in junit format. If the reporting is set `pretty-printer`, the exclusion seems to be taken in account and the risk score is 0. Also, its seems that the exclusion is taken in account but not printed in the right way. The failed resources are marked as 0 but it is still marked as a failure in Azure DevOps. Also it seems that the exclusion property is set to 0 while the test is being excluded.

**Example**
```sh
kubescape scan framework nsa \
--keep-local \
--format junit \
--exceptions exceptions.json \
--fail-threshold 0 \
--output example.xml \
deploy.yaml
```
```yaml
# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
```
```json
[
  {
    "name": "Allow Non-root containers",
    "policyType": "postureExceptionPolicy",
    "resources": [
      {
        "designatorType": "Attributes",
        "attributes": {
          "namespace": ".*"
        }
      }
    ],
    "posturePolicies": [
      {
        "controlName": "Non-root containers"
      }
    ]
  }
]
```
```xml
<!-- example.xml (snipped) -->
<testsuites>
    <testsuite tests="26" time="" name="NSA" resources="1" excluded="0" filed="1">
        <properties></properties>
        <testcase classname="Kubescape" name="Non-root containers" time="0001-01-01 00:00:00 +0000 UTC" resources="1" excluded="0" filed="0">
            <failure message="0 resources failed" type="">&#xA;</failure>
        </testcase>
    </testsuite>
</testsuites>
```

**Solution**
-
