### ISSUE TITLE
Labels controls always triggered

### ISSUE THREAD

**Issue by mafalda-g-nunes** [armosec/kubescape#494]
I'm using Kubescape (installed through [install.sh](https://github.com/armosec/kubescape/blob/master/install.sh)) to scan the following document:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test-namespace
  labels:
    app: test
    tier: backend
    phase: dev
    version: "1.0.0"
    owner: test-owner
    env: dev
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: test-project
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/created-by: test-creator
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2
  template:
    metadata:
      labels:
        app: test
        tier: backend
        phase: dev
        version: "1.0.0"
        owner: test-owner
        env: dev
        app.kubernetes.io/name: test
        app.kubernetes.io/instance: test-instance
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: test-project
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/created-by: test-creator
    spec:
      containers:
        - name: test
          imagePullPolicy: Never
          image: local/test:dev
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            requests:
              memory: 1Mi
              cpu: 200m
            limits:
              memory: 2Mi
              cpu: 250m
          securityContext:
            runAsNonRoot: true
            runAsUser: 100000
            runAsGroup: 100000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
```

I defined all default labels, but the "K8s common labels usage" and "Label usage for resources" controls always fail when I scan the file. Is there any mistake regarding the labels defined on the Kubernetes manifest previously described?

I don't know if this is the fix, but I realized that by changing `"configInputs": null` to `"configInputs": ["settings.postureControlInputs.recommendedLabels"]` on the `label-usage-for-resources` rule in the `.kubescape/DevOpsBest.json` file, that control no longer fails (equivalent for `k8sRecommendedLabels`).
