### ISSUE TITLE
EKS: failed to collect cloud data - input member name must not be empty

### ISSUE THREAD

**Issue by zhujik** [armosec/kubescape#504]
wenn running kubescape scan, kubescape is not able to collect EKS cluster data and therefore skips all related tests. The error is:

Call:
```
kubescape scan  framework nsa --enable-host-scan --logger debug
```
Output:
```
{"level":"debug","ts":"2022-05-09T11:33:43+02:00","msg":"Collecting cloud data"}
{"level":"debug","ts":"2022-05-09T11:33:43+02:00","msg":"cloud","cluster":"arn:aws:eks:eu-north-1:123456789012:cluster-my-cluster","clusterName":"arn:aws:eks:eu-north-1:123456789012:cluster-my-cluster","provider":"eks"}
{"level":"debug","ts":"2022-05-09T11:33:43+02:00","msg":"failed to get descriptive information","error":"operation error EKS: DescribeCluster, serialization failed: serialization failed: input member name must not be empty"}
```

More information:
following env vars are set and valid:
```
AWS_DEFAULT_REGION=eu-north-1
AWS_SECRET_ACCESS_KEY=...
AWS_ACCESS_KEY_ID=...
AWS_SESSION_TOKEN=...
KS_CLOUD_REGION=eu-north-1
KS_CLOUD_PROVIDER=eks
KUBECONFIG=/home/zhujik/.kube/my-cluster
```

Content of kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: .....
    server: https://abcdefg.eu-north-1.eks.amazonaws.com
  name: arn:aws:eks:eu-north-1:123456789012:cluster/my-cluster
contexts:
- context:
    cluster: arn:aws:eks:eu-north-1:123456789012:cluster/my-cluster
    user: arn:aws:eks:eu-north-1:123456789012:cluster/my-cluster
  name: arn:aws:eks:eu-north-1:123456789012:cluster/my-cluster
current-context: arn:aws:eks:eu-north-1:123456789012:cluster/my-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-north-1:123456789012:cluster/my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-north-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      - --role
      - arn:aws:iam::123456789012:role/ClusterAccessRole
      command: aws
```

Error seems to be somewhere around https://github.com/armosec/k8s-interface/blob/e078680959e241b1ebd0bdf145a19e9c5227d8c3/cloudsupport/v1/ekssupport.go#L42
