### ISSUE TITLE
"K8s common labels usage" Label Always Fails

### ISSUE THREAD

**Issue by EdSwArchitect** [armosec/kubescape#539]
Hello, I have the "K8s common labels usage" control enabled, but the scan **_ALWAYS_** fails, even when all values are used. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: my-example
  labels:
    app: my-example
    app.kubernetes.io/instance: my-example
    app.kubernetes.io/name: test-instance
    app.kubernetes.io/instance: test-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: test-project
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/created-by: test-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-example
      app.kubernetes.io/instance: my-example
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: test-project
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/created-by: test-creator
  template:
    metadata:
      labels:
        app: my-example
        access: internal
        app.kubernetes.io/instance: my-example
        app.kubernetes.io/instance: test-instance
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: test-project
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/created-by: test-creator
```

[I see this closed issue was the "fix"](https://github.com/armosec/kubescape/issues/494), but I still get the error after upgrading.

```shell
$ kubescape -v
kubescape version v2.0.158
```

I'm on MacOS

**Comment by dwertent** [comment]
Thank you @EdSwArchitect for reporting.

**Comment by EdSwArchitect** [comment]
Additional information, I installed on MacOS using Brew.

**Comment by Moshe-Rappaport-CA** [comment]
Hi @EdSwArchitect 
Thank you for reporting.

When I ran kubescape with control C-0077 (K8s common labels usage), it did not fail.
I also ran it on MacOS

kubescape version: 
```shell
$ kubescape -v
kubescape version v2.0.158
```
file: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: my-example
  labels:
    app: my-example
    app.kubernetes.io/instance: my-example
    app.kubernetes.io/name: test-instance
    app.kubernetes.io/instance: test-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: test-project
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/created-by: test-creator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-example
      app.kubernetes.io/instance: my-example
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: test-project
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/created-by: test-creator
  template:
    metadata:
      labels:
        app: my-example
        access: internal
        app.kubernetes.io/instance: my-example
        app.kubernetes.io/instance: test-instance
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: test-project
        app.kubernetes.io/managed-by: kubectl
        app.kubernetes.io/created-by: test-creator
```

I ran:
```shell
$ kubescape scan control c-0077 ./example.yaml -v
```
And I got the result that the control did not fail.

![image](https://user-images.githubusercontent.com/89577611/177041380-749d97a0-2cc9-4873-a71e-03c78d609813.png)

Are you using local-artifacts? Maybe this is the difference? 
What was the exact command you issued?
